import color from 'color';
export const lightTheme = {
  accentColor: '#ECECEC', // Inputs
  bodyColor: '#FCFCFC',
  inputColorLight: '#f3f3f3',
  inputColorDark: '#f3f3f3',
  overlayColor: '#FBFBFB',
  headingColor: '#252525',
  subHeading: '#3B3B3B',
  textColor: 'rgba(15,15,15,.7)',
  shadow: '0px 0px 6px 0px rgb(159,159,159)',
  highlightColor: '#b11e29',
  highlightColorText: '#fff',
  btnPrimaryLight: '#b11e29',
  btnPrimaryDark: '#b11e29',
  btnBorder: 'none',
  green: '#0B9B23',
  btnText: '#fff',
  dangerRed: '#b72b2b',
};

export const darkTheme = {
  mainColor: '#3B3B3B',
  accentColor: '#5B5B5B',
  inputColorLight: '#505050',
  inputColorDark: '#6f6f6f',
  btnBorder: '#D8D8D8',
  bodyColor: '#3B3B3B',
  overlayColor: '#5B5B5B',
  headingColor: '#FFF',
  subHeading: '#D8D8D8',
  textColor: '#FFF',
  shadow: '',
  highlightColor: '#2d2d2d',
  highlightColorText: '#fff',
  btnPrimaryLight: '#797979',
  btnPrimaryDark: '#3B3B3B',
  green: '#1AD439',
  btnText: '#fff',
  dangerRed: color('#b72b2b').lighten(0.5).toString(),
};
